# Uhm, thanks to @buchdag for pretty much all the source, I guess?

version: "3"

services:
    nginx:
        image: jwilder/nginx-proxy:alpine
        container_name: nginx-proxy
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - conf:/etc/nginx/conf.d
          - vhost:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
          - certs:/etc/nginx/certs:ro
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./custom.conf:/etc/nginx/conf.d/custom.conf
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
        restart: on-failure

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion:latest
        container_name: nginx-proxy-le
        depends_on:
          - nginx
        volumes:
          - conf:/etc/nginx/conf.d
          - vhost:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
          - certs:/etc/nginx/certs
          - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: on-failure

volumes:
    conf:
    vhost:
    html:
    certs:

# Do not forget to 'docker network create nginx-proxy' before launch
# and to add '--network nginx-proxy' to proxyed containers.

networks:
    default:
        external:
            name: nginx-proxy
